### ISSUE TITLE
Attempting to save a product without a required field should identify the field that failed

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-admin#114]
When trying to save a product that doesn't have a title, I receive a toast alert letting me know that the title is required, but the field does not get highlighted, nor does the panel open to the product edit panel when I try to save a product without a title.

The UI should identify the field that failed and open the action view panel to the correct section as it does when attempting to save an invalid field in a variant.

![image](https://user-images.githubusercontent.com/1203639/31038057-d6c566b0-a531-11e7-8791-40116e4cf709.png)

Server error is caused as well. We should attempt to catch this invalid product before sending it to the server.
```
Exception while invoking method 'revisions/publish' Error: Product Title is required
    at getErrorObject (packages/aldeed_collection2-core.js:480:15)
    at [object Object].doValidate (packages/aldeed_collection2-core.js:462:13)
    at [object Object].Mongo.Collection.(anonymous function) (packages/aldeed_collection2-core.js:214:25)
    at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user.js:325:19)
    at [object Object].revisionsPublish (imports/plugins/core/revisions/server/methods.js:119:32)
    at packages/check.js:128:16
    at [object Object].EVp.withValue (packages/meteor.js:1134:15)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
    at packages/ddp-server/livedata_server.js:719:19
    at [object Object].EVp.withValue (packages/meteor.js:1134:15)
    at packages/ddp-server/livedata_server.js:717:46
    at [object Object].EVp.withValue (packages/meteor.js:1134:15)
    at packages/ddp-server/livedata_server.js:715:46
    at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
Sanitized and reported to the client as: Product Title is required [400]
```

**Comment by aldeed** [comment]
Referenced UI is gone
